brew 'neovim'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'sk'
brew 'z'
brew 'rbenv'
brew 'youtube-dl'
brew 'postgresql@14'
brew 'tmux'
brew 'bat'
brew 'starship'
brew 'rustup-init'

# docker
# brew 'docker'
# brew 'docker-compose'
# brew 'docker-credential-helper'
# brew 'buildkit'

cask 'vlc'
cask 'notion'
cask 'rectangle'
# cask 'iterm2'
