#!/usr/bin/env ruby

require 'json'
require 'shellwords'

repo_root = `git rev-parse --show-toplevel`.chomp

Dir.chdir(repo_root)

all = Dir.glob('{.,}*').reject do |f|
  %w[. .DS_Store .git .gitignore scripts tmp].include?(f)
end

grouped = all.group_by { |f| File.file?(f) }

files = grouped[true]

dirs = grouped[false]

puts
puts "FILES\n-----\n"

puts files

diffs = { not_in_home: [], not_in_repo: [], diff: [] }

files.each do |f|
  b = File.basename(f)
  h = File.join(Dir.home, b)

  unless File.exist?(h)
    diffs[:not_in_home] << [f, h]
    next
  end

  unless system('diff', '-q', f, h)
    diffs[:diff] << [h, f]
  end
end

puts
puts "DIRS\n-----\n"

puts dirs

dirs.each do |dir|
  lines = `diff -qrs #{dir} ~/#{dir}`.lines(chomp: true)

  lines.each do |line|
    case line
    in /identical/
      next
    in /Only in #{Dir.home}\/([^:]*):\s*(\S.*)/
      diffs[:not_in_repo] << [
        File.join(Dir.home, $1, $2),
        File.join($1, $2),
      ]
    in /Only in ([^:]*):\s*(\S.*)/
      diffs[:not_in_home] << [
        File.join($1, $2),
        File.join(Dir.home, $1, $2),
      ]
    in /Files (.*) and (.*) differ/
      diffs[:diff] << [$1, $2]
    else
      puts "ELSE #{line}"
    end
  end
end



File.write 'sync.json', JSON.pretty_generate(diffs)

script = ["#!/bin/bash" ,'']

diffs[:not_in_repo].each do |args|
  dirname = File.dirname(args.last)

  unless Dir.exist?(dirname)
    script << ''
    script << format('mkdir -pv %s', dirname.shellescape)
  end

  script << format('cp -v %s %s', *args.map(&:shellescape))
end

script << ''

diffs[:diff].each do |args|
  args = args.reverse unless File.absolute_path?(args.first)
  script << format('vim -d %s %s', *args.map(&:shellescape))
end

File.unlink('sync.sh') if File.exist?('sync.sh')
File.write('sync.sh', script.join("\n"))

File.chmod(777, 'sync.sh')

