# Don't print a new line at the start of the prompt
# add_newline = true

# makes prompt a single line
# [line_break]
# disabled = false

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = false

[cmd_duration]
min_time = 100_000  # Show command duration over 10,000 milliseconds (= 10 sec)
format = "took [$duration]($style)"

[character]
error_symbol = "[❯](bold red)"

# Clear visibility for exit codes
[status]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[git_status]
stashed = ''
format = '(\([$staged](green)[$conflicted$stashed$deleted$renamed$modified$untracked](red)\) )'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[time]
disabled = false
time_format = '%Y-%m-%d %H:%M:%S '
format = "[$time]($style)"
